services:
  api_interact: 
    build: ./src/api/interact_model/
    image: neevaiti/api_interact:latest
    ports:
      - 12600:12600
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - API_MODEL_KEY=${API_MODEL_KEY}
      - API_KEY=${API_KEY}
    networks:
      - api_network

  api_model:
    build: ./src/api/model/
    image: neevaiti/api_model:latest
    ports:
      - 12500:12500
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - API_MODEL_KEY=${API_MODEL_KEY}
      - API_KEY=${API_KEY}
    networks:
      - api_network
    volumes:
      - models:/app/models

networks:
  api_network:
    driver: bridge

volumes:
  models: