version: '3.8'
services:

  api_interact: 
    build: ./src/api/interact_model/
    ports:
      - 8060:8060
    # command: sh -c "uvicorn api:app --host 0.0.0.0 --port 8060"

  api_model:
    build: ./src/api/model/
    ports:
      - 8050:8050
    # command: sh -c "uvicorn api:app --host 0.0.0.0 --port 8050"

