services:
  api_interact: 
    build: ./src/api/interact_model/
    ports:
      - 12600:12600
    env_file:
      - ./src/api/interact_model/.env
    networks:
      - api_network

  api_model:
    build: ./src/api/model/
    ports:
      - 12500:12500
    env_file:
      - ./src/api/model/.env
    networks:
      - api_network
    volumes:
      - ./models:/models

networks:
  api_network:
    driver: bridge