# Generated by Django 5.1.1 on 2024-10-04 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safeurl', '0002_modelversion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelVersion',
        ),
    ]
