name: CD Pipeline

on:
  push:
    branches:
      - main  # Déployer sur la branche main

jobs:
  build_and_push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PORT: ${{ secrets.DB_PORT }}
      API_MODEL_KEY: ${{ secrets.API_MODEL_KEY }}
      API_KEY: ${{ secrets.API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push Docker images
        run: |
          DB_HOST=${{ secrets.DB_HOST }} \
          DB_USER=${{ secrets.DB_USER }} \
          DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
          DB_NAME=${{ secrets.DB_NAME }} \
          DB_PORT=${{ secrets.DB_PORT }} \
          API_MODEL_KEY=${{ secrets.API_MODEL_KEY }} \
          API_KEY=${{ secrets.API_KEY }} \
          docker compose build
          docker compose push

  deploy:
    name: Deploy to Azure Container Instances
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy API Interact to Azure Container Instances
        uses: azure/aci-deploy@v1
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          dns-name-label: api-interact  # Unique DNS label for the API Interact
          image: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/api_interact:latest
          registry-login-server: docker.io
          registry-username: ${{ secrets.DOCKERHUB_USERNAME }}
          registry-password: ${{ secrets.DOCKERHUB_PASSWORD }}
          name: api-interact-container
          location: francecentral
          ports: '12600'
          secure-environment-variables: |
            DB_HOST=${{ secrets.DB_HOST }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_NAME=${{ secrets.DB_NAME }}
            DB_PORT=${{ secrets.DB_PORT }}
            API_MODEL_KEY=${{ secrets.API_MODEL_KEY }}
            API_KEY=${{ secrets.API_KEY }}

      - name: Deploy Model API to Azure Container Instances
        uses: azure/aci-deploy@v1
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          dns-name-label: api-model  # Unique DNS label for the model API
          image: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/api_model:latest
          registry-login-server: docker.io
          registry-username: ${{ secrets.DOCKERHUB_USERNAME }}
          registry-password: ${{ secrets.DOCKERHUB_PASSWORD }}
          name: api-model-container
          location: francecentral
          ports: '12500'
          secure-environment-variables: |
            DB_HOST=${{ secrets.DB_HOST }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_NAME=${{ secrets.DB_NAME }}
            DB_PORT=${{ secrets.DB_PORT }}
            API_MODEL_KEY=${{ secrets.API_MODEL_KEY }}
            API_KEY=${{ secrets.API_KEY }}