name: CD Pipeline

on:
  push:
    branches:
      - main  # Déployer sur la branche main

jobs:
  build_and_push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PORT: ${{ secrets.DB_PORT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push api_model image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/api_model:latest -f src/api/model/Dockerfile .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/api_model:latest

      - name: Build and Push api_interact image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/api_interact:latest -f src/api/interact_model/Dockerfile .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/api_interact:latest

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy with Docker Compose
        run: |
          docker-compose -f docker-compose.yml up --build -d
