name: CI Pipeline

on:
  push:
    branches:
      - develop

jobs:
  test:
    name: Run Tests with SQLite in-memory
    runs-on: ubuntu-latest
    env:
      IS_TEST: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.13'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Pytest for non-Django projects
        run: pytest src/api/interact_model/tests src/api/model/tests

      - name: Run Django Tests
        run: |
          cd src/website/safeurl
          pytest

  build:
    name: Build and Push Docker Images (for all services)
    runs-on: ubuntu-latest
    needs: test  # S'exécute après la réussite des tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push Docker images
        run: |
          docker compose build
          docker compose push


