name: CI Pipeline

on:
  push:
    branches:
      - develop  # Exécuter sur la branche develop

jobs:
  test:
    name: Run Tests with SQLite in-memory
    runs-on: ubuntu-latest
    env:
      IS_TEST: true  # Mode test pour utiliser SQLite

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.13'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Tests
        run: pytest

  build:
    name: Build Docker Images (for testing)
    runs-on: ubuntu-latest
    needs: test
    env:
      IS_TEST: false  # Mode production
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PORT: ${{ secrets.DB_PORT }}


    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker images
        run: |
          docker build -t api_model_test -f src/api/model/Dockerfile .
          docker build -t api_interact_test -f src/api/interact_model/Dockerfile .
