name: CI Pipeline

on:
  push:
    branches:
      - develop

jobs:
  test:
    name: Run Tests with SQLite in-memory
    runs-on: ubuntu-latest
    env:
      IS_TEST: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.13'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Pytest for API Tests
        run: pytest src/api/interact_model/tests src/api/model/tests --maxfail=1

      - name: Run Django Tests
        run: |
          cd src/website/safeurl
          pytest --maxfail=3